# INTRODUCTION TO SCIKIT-LEARN (sklearn)

# An end-to-end Scikit-learn worklow

In [2]:
#Standard Imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
# 1. Get the data ready 
heart_disease = pd.read_csv("heart.csv")
heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [4]:
X = heart_disease.drop('target',axis=1)
# create X (features matrix)
X

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3

In [5]:
# Create Y(label matrix / labels)
Y = heart_disease['target']
Y

0       0
1       0
2       0
3       0
4       0
       ..
1020    1
1021    0
1022    0
1023    1
1024    0
Name: target, Length: 1025, dtype: int64

In [6]:
# To deal with warnings 
import warnings
warnings.filterwarnings("ignore") 
# a band-aid solution for warning pop-ups
#“Do not display any warning messages.”
#Sometimes libraries (like pandas or sklearn) show many warnings that clutter the output.

In [7]:
# 2.Choose the right model and hyperparameters
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()

# we ll keep the default hyperparameters 
clf.get_params()
# Parameters = learned by the model
# Hyperparameters = chosen by you
#Hyperparameters are settings you choose before training that control how a model learns.

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [8]:
# 3.Fit the model to the training data
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

In [9]:
clf.fit(X_train, Y_train);   #.fit-> train the model 
# the model studies patterns in x_train and tries to understand how to relate to y_train

In [10]:
y_preds =  clf.predict(X_test)
y_preds
# model guesses the answers for new data

array([0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0])

In [11]:
Y_test

452    0
544    1
815    1
694    0
709    0
      ..
832    1
786    0
937    0
165    0
394    0
Name: target, Length: 205, dtype: int64

In [12]:
# 4. Evaluate the model on the training data and test data 
clf.score(X_train, Y_train)
# how well did the model learn the training data

1.0

In [13]:
clf.score(X_test, Y_test)
# This calculates accuracy on test data

1.0

In [14]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(classification_report(Y_test,y_preds))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       107
           1       1.00      1.00      1.00        98

    accuracy                           1.00       205
   macro avg       1.00      1.00      1.00       205
weighted avg       1.00      1.00      1.00       205

In [15]:
confusion_matrix(Y_test, y_preds)

array([[107,   0],
       [  0,  98]])

In [16]:
accuracy_score(Y_test, y_preds)

1.0

In [17]:
# 5. improve model accuracy 
# try the model accuracy with different n_estimators 
np.random.seed(14) # ensures the results are reproducible 
for i in range(10, 200, 10):
  print(f'Trying model with {i} estimators')
  clf = RandomForestClassifier(n_estimators = i).fit(X_train, Y_train)
  print(f'Model accuracy on the test set: {clf.score(X_test, Y_test)* 100:.2f}%')
    # .score() = predict + calculate accuracy

Trying model with 10 estimators
Model accuracy on the test set: 99.02%
Trying model with 20 estimators
Model accuracy on the test set: 98.54%
Trying model with 30 estimators
Model accuracy on the test set: 100.00%
Trying model with 40 estimators
Model accuracy on the test set: 100.00%
Trying model with 50 estimators
Model accuracy on the test set: 100.00%
Trying model with 60 estimators
Model accuracy on the test set: 100.00%
Trying model with 70 estimators
Model accuracy on the test set: 100.00%
Trying model with 80 estimators
Model accuracy on the test set: 100.00%
Trying model with 90 estimators
Model accuracy on the test set: 100.00%
Trying model with 100 estimators
Model accuracy on the test set: 100.00%
Trying model with 110 estimators
Model accuracy on the test set: 100.00%
Trying model with 120 estimators
Model accuracy on the test set: 100.00%
Trying model with 130 estimators
Model accuracy on the test set: 100.00%
Trying model with 140 estimators
Model accuracy on the test set: 100.00%
Trying model with 150 estimators
Model accuracy on the test set: 100.00%
Trying model with 160 estimators
Model accuracy on the test set: 100.00%
Trying model with 170 estimators
Model accuracy on the test set: 100.00%
Trying model with 180 estimators
Model accuracy on the test set: 100.00%
Trying model with 190 estimators
Model accuracy on the test set: 100.00%

In [18]:
# 6. Save a model amd load it 
import pickle 
# pickle is a Python library used to save objects to a file.
pickle.dump(clf, open('random_forest_model_1.pkl','wb'))
#This line:
#Takes your trained model clf
#Converts it into a special binary format
#Saves it into a file called: random_forest_model_1.pkl
#w → write; b → binary mode
#We must use binary mode because pickle stores data in binary format.
# We save the model so we don’t have to retrain it every time we run the program.
# A pickle (.pkl) file is a file that stores a trained Python object (like a model) in binary form so it can be loaded later.
# We use binary form because it allows Python to store the full complex model object exactly as it exists in memory.

In [19]:
loaded_model = pickle.load(open('random_forest_model_1.pkl','rb'))
loaded_model.score(X_test,Y_test)

1.0

# 1.Getting our data ready to be used with machine learning

In [20]:
heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [21]:
X = heart_disease.drop('target',axis =1)
Y = heart_disease['target']

In [22]:
# split the data to test and train
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size =0.2)

In [23]:
X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

((820, 13), (205, 13), (820,), (205,))

Clean data -> transform data -> reduce data

### 1.1 Make sure its all numerical

In [24]:
car_sales= pd.read_csv('car-sales-extended.csv')
car_sales.head()

     Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [25]:
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price             int64
dtype: object

We are going to try ans see whether the Model can predict the price of the car with just the Make, Colour, Odometer value and door

In [30]:
# split into X and Y 
X=car_sales.drop('Price',axis=1)
Y = car_sales['Price']
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2)

In [31]:
X_train.shape , X_test.shape, Y_train.shape, Y_test.shape

((800, 4), (200, 4), (800,), (200,))

In [34]:
# build the machine learning model 
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()
#model.fit(X_train, Y_train)
#model.score(X_test, y_test)
# error comes as 'could not convert string to float: 'Honda'

## Examples of Preprocessing Tasks

### 1. Cleaning Data
- Removing symbols like `$` or `,`
- Fixing incorrect values

### 2. Handling Missing Values
- Filling missing data with mean/median
- Removing rows

### 3. Encoding Categorical Data
- Converting text like `"Red"` or `"Toyota"` into numbers
- Example: using `OneHotEncoder`

### 4. Scaling Numeric Data
- Making values comparable (e.g., `0–1` range)

### 5. Feature Selection or Transformation
- Choosing useful columns for the model

In [ ]:
# Turn the categories into number 
from sklearn.preprocessing import OneHotEncoder 
#Preprocessing is the step where you clean and transform raw data into a format that a machine learning model can understand and use effectively.
#OneHotEncoder converts categorical values into multiple binary (0/1) columns so machine learning models can use them.
from sklearn.compose import ColumnTransformer 
#