# INTRODUCTION TO SCIKIT-LEARN (sklearn)

# An end-to-end Scikit-learn worklow

In [47]:
import pandas as pd
import numpy as np

In [48]:
# 1. Get the data ready 
heart_disease = pd.read_csv("heart.csv")
heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [49]:
X = heart_disease.drop('target',axis=1)
# create X (features matrix)
X

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3

In [50]:
# Create Y(label matrix / labels)
Y = heart_disease['target']
Y

0       0
1       0
2       0
3       0
4       0
       ..
1020    1
1021    0
1022    0
1023    1
1024    0
Name: target, Length: 1025, dtype: int64

In [51]:
# To deal with warnings 
import warnings
warnings.filterwarnings("ignore") 
# a band-aid solution for warning pop-ups
#“Do not display any warning messages.”
#Sometimes libraries (like pandas or sklearn) show many warnings that clutter the output.

In [52]:
# 2.Choose the right model and hyperparameters
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()

# we ll keep the default hyperparameters 
clf.get_params()
# Parameters = learned by the model
# Hyperparameters = chosen by you
#Hyperparameters are settings you choose before training that control how a model learns.

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [53]:
# 3.Fit the model to the training data
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

In [54]:
clf.fit(X_train, Y_train);   #.fit-> train the model 
# the model studies patterns in x_train and tries to understand how to relate to y_train

In [55]:
y_preds =  clf.predict(X_test)
y_preds
# model guesses the answers for new data

array([0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 0])

In [56]:
Y_test

29     0
845    0
812    0
432    1
652    1
      ..
172    1
99     1
683    0
482    0
530    0
Name: target, Length: 205, dtype: int64

In [57]:
# 4. Evaluate the model on the training data and test data 
clf.score(X_train, Y_train)
# how well did the model learn the training data

1.0

In [58]:
clf.score(X_test, Y_test)
# This calculates accuracy on test data

0.9853658536585366

In [59]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(classification_report(Y_test,y_preds))

              precision    recall  f1-score   support

           0       1.00      0.97      0.98        93
           1       0.97      1.00      0.99       112

    accuracy                           0.99       205
   macro avg       0.99      0.98      0.99       205
weighted avg       0.99      0.99      0.99       205

In [60]:
confusion_matrix(Y_test, y_preds)

array([[ 90,   3],
       [  0, 112]])

In [61]:
accuracy_score(Y_test, y_preds)

0.9853658536585366

In [62]:
# 5. improve model accuracy 
# try the model accuracy with different n_estimators 
np.random.seed(14) # ensures the results are reproducible 
for i in range(10, 200, 10):
  print(f'Trying model with {i} estimators')
  clf = RandomForestClassifier(n_estimators = i).fit(X_train, Y_train)
  print(f'Model accuracy on the test set: {clf.score(X_test, Y_test)* 100:.2f}%')
    # .score() = predict + calculate accuracy

Trying model with 10 estimators
Model accuracy on the test set: 98.54%
Trying model with 20 estimators
Model accuracy on the test set: 98.54%
Trying model with 30 estimators
Model accuracy on the test set: 98.54%
Trying model with 40 estimators
Model accuracy on the test set: 98.54%
Trying model with 50 estimators
Model accuracy on the test set: 97.07%
Trying model with 60 estimators
Model accuracy on the test set: 100.00%
Trying model with 70 estimators
Model accuracy on the test set: 97.07%
Trying model with 80 estimators
Model accuracy on the test set: 98.54%
Trying model with 90 estimators
Model accuracy on the test set: 98.54%
Trying model with 100 estimators
Model accuracy on the test set: 98.54%
Trying model with 110 estimators
Model accuracy on the test set: 100.00%
Trying model with 120 estimators
Model accuracy on the test set: 98.54%
Trying model with 130 estimators
Model accuracy on the test set: 98.54%
Trying model with 140 estimators
Model accuracy on the test set: 97.07%
Trying model with 150 estimators
Model accuracy on the test set: 97.07%
Trying model with 160 estimators
Model accuracy on the test set: 98.54%
Trying model with 170 estimators
Model accuracy on the test set: 97.07%
Trying model with 180 estimators
Model accuracy on the test set: 98.54%
Trying model with 190 estimators
Model accuracy on the test set: 98.54%

In [63]:
# 6. Save a model amd load it 
import pickle 
# pickle is a Python library used to save objects to a file.
pickle.dump(clf, open('random_forest_model_1.pkl','wb'))
#This line:
#Takes your trained model clf
#Converts it into a special binary format
#Saves it into a file called: random_forest_model_1.pkl
#w → write; b → binary mode
#We must use binary mode because pickle stores data in binary format.
# We save the model so we don’t have to retrain it every time we run the program.
# A pickle (.pkl) file is a file that stores a trained Python object (like a model) in binary form so it can be loaded later.
# We use binary form because it allows Python to store the full complex model object exactly as it exists in memory.

In [64]:
loaded_model = pickle.load(open('random_forest_model_1.pkl','rb'))
loaded_model.score(X_test,Y_test)

0.9853658536585366

# 1.Getting our data ready to be used with machine learning

In [65]:
heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [66]:
X = heart_disease.drop('target',axis =1)
Y = heart_disease['target']

In [67]:
# split the data to test and train
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size =0.2)

In [68]:
X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

((820, 13), (205, 13), (820,), (205,))

Clean data -> transform data -> reduce data

### 1.1 Make sure its all numerical

In [69]:
car_sales= pd.read_csv('car-sales-extended.csv')
car_sales.head()

     Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [70]:
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price             int64
dtype: object

We are going to try ans see whether the Model can predict the price of the car with just the Make, Colour, Odometer value and door

In [71]:
# split into X and Y 
X=car_sales.drop('Price',axis=1)
Y = car_sales['Price']
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2)

In [72]:
X_train.shape , X_test.shape, Y_train.shape, Y_test.shape

((800, 4), (200, 4), (800,), (200,))

In [73]:
# build the machine learning model 
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()
#model.fit(X_train, Y_train)
#model.score(X_test, y_test)
# error comes as 'could not convert string to float: 'Honda'

## Examples of Preprocessing Tasks

### 1. Cleaning Data
- Removing symbols like `$` or `,`
- Fixing incorrect values

### 2. Handling Missing Values
- Filling missing data with mean/median
- Removing rows

### 3. Encoding Categorical Data
- Converting text like `"Red"` or `"Toyota"` into numbers
- Example: using `OneHotEncoder`

### 4. Scaling Numeric Data
- Making values comparable (e.g., `0–1` range)

### 5. Feature Selection or Transformation
- Choosing useful columns for the model

In [74]:
# Turn the categories into number 
from sklearn.preprocessing import OneHotEncoder 
#Preprocessing is the step where you clean and transform raw data into a format that a machine learning model can understand and use effectively.
#OneHotEncoder converts categorical values into multiple binary (0/1) columns so machine learning models can use them.
from sklearn.compose import ColumnTransformer 
#ColumnTransformer allows you to apply different preprocessing steps to different columns in a dataset.
#ColumnTransformer from scikit-learn is a preprocessing utility that allows you to apply different transformations to different columns of a dataset at the same time.
# Categorical columns → Encoding (e.g., OneHotEncoder)
#Numeric columns → Scaling (e.g., StandardScaler)
#One-Hot Encoding: Converts each category into separate binary columns (0 or 1).
#Label Encoding: Converts categories into integer labels (0,1,2…).

In [75]:
car_sales

       Make Colour  Odometer (KM)  Doors  Price
0     Honda  White          35431      4  15323
1       BMW   Blue         192714      5  19943
2     Honda  White          84714      4  28343
3    Toyota  White         154365      4  13434
4    Nissan   Blue         181577      3  14043
..      ...    ...            ...    ...    ...
995  Toyota  Black          35820      4  32042
996  Nissan  White         155144      3   5716
997  Nissan   Blue          66604      4  31570
998   Honda  White         215883      4   4001
999  Toyota   Blue         248360      4  12732

[1000 rows x 5 columns]

In [76]:
categorical_features =['Make','Colour','Doors'] # You are creating a list of columns that contain categorical data.
one_hot = OneHotEncoder() #You are creating a list of columns that contain categorical data.

transformer = ColumnTransformer([('one_hot', one_hot, categorical_features)], remainder='passthrough')
# create a columTransformer to apply apply OneEncoder to the categorial columns
# syntax = ('name_of_transform', transformation_method, columns_to_apply)

transformed_X = transformer.fit_transform(X)
# Fit the transformer to the dataset and transform the categorical columns 

transformed_X
# display the transfered dataset after encoding

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]], shape=(1000, 13))

In [77]:
pd.DataFrame(transformed_X)

      0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

In [78]:
# another way to do this is with pandas dummies 
dummies = pd.get_dummies(car_sales[['Make','Colour','Doors']])
dummies

,Doors,Make_BMW,Make_Honda,Make_Nissan,Make_Toyota,Colour_Black,Colour_Blue,Colour_Green,Colour_Red,Colour_White
0,4,False,True,False,False,False,False,False,False,True
1,5,True,False,False,False,False,True,False,False,False
2,4,False,True,False,False,False,False,False,False,True
3,4,False,False,False,True,False,False,False,False,True
4,3,False,False,True,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...
995,4,False,False,False,True,True,False,False,False,False
996,3,False,False,True,False,False,False,False,False,True
997,4,False,False,True,False,False,True,False,False,False
998,4,False,True,False,False,False,False,False,False,True
999,4,False,False,False,True,False,True,False,False,False

In [79]:
# fit the model 
np.random.seed(42)
X_train,X_test, Y_train, Y_test = train_test_split(transformed_X, Y, test_size=0.2)
model.fit(X_train, Y_train)
model.score(X_test, Y_test)

0.3235867221569877

### 1.2 What if there was missing value?
1. Fill the missing vakues with some value
2. Remove the samples with the missing data altogether

In [80]:
car_sales_missing = pd.read_csv('car-sales-extended-missing-data.csv')
car_sales_missing

       Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

In [81]:
car_sales_missing.isna().sum()
#It tells you how many missing values (NaN) are present in each column of the dataset.

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [82]:
# Fill the make column 
car_sales_missing['Make'].fillna('missing', inplace=True)
car_sales_missing['Colour'].fillna('missing', inplace = True)
car_sales_missing['Doors'].fillna(4, inplace=True)
car_sales_missing['Odometer (KM)'].fillna(car_sales_missing['Odometer (KM)'].mean(),inplace = True)

In [83]:
car_sales_missing.isna().sum()

Make              0
Colour            0
Odometer (KM)     0
Doors             0
Price            50
dtype: int64

In [84]:
# remove rows with missing values 
car_sales_missing.dropna(inplace = True)

In [85]:
car_sales_missing.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [89]:
X = car_sales_missing.drop('Price', axis =1)
Y = car_sales_missing['Price']
# convert the categories inot numerical values 
categorical_features = ['Make', 'Colour','Doors']
one_hot = OneHotEncoder()
transformer = ColumnTransformer([('one_hot', one_hot, categorical_features)], remainder ='passthrough')
transformed_X = transformer.fit_transform(X)
X_train, X_test , Y_train, Y_test = train_test_split(transformed_X,Y,test_size = 0.2)

### option 2 : Fill the missing values with Scikit-Learn

In [90]:
car_sales_missing = pd.read_csv('car-sales-extended-missing-data.csv')
car_sales_missing.head()

     Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [91]:
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [92]:
# drop the rows with no values in thr price column 
car_sales_missing.dropna(subset=['Price'],inplace = True)
car_sales_missing.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

In [93]:
from sklearn.model_selection import train_test_split
X = car_sales_missing.drop('Price', axis  =1)
Y = car_sales_missing['Price']
np.random.seed(25)
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2)

In [94]:
X.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
dtype: int64

In [ ]:
# fill missing values with Scikit-Learn
from sklearn.impute import SimplwImputer 
from sklearn.compose import ColumnTransformer 

# Fill categorical values with 'missing' & numerical values with mean